name: Get commands

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
  pull_request:

jobs:
  GetCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm ci
        run: npm ci
      - name: get CPM commands
        run: npm run commands:cpm
      - name: npm run build
        run: npm run build
      - uses: EndBug/add-and-commit@v6
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: "docs/.vuepress/public/assets/cpmCommands.json"

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "Update commands reference"

          # Token to use for pushing the commit. The default value won't trigger any workflows, you need to use a Personal Access Token for that.
          # Default: secrets.GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}
